alias godot='cd /mnt/seagate/workspace/godot/projects'
alias seagate='cd /mnt/seagate'
alias coding='cd /mnt/seagate/workspace/coding/projects'
alias actvenv='source venv/bin/activate'
alias actenv='source env/bin/activate'
alias nvconf='cd ~/.config/nvim/'
alias kswitcher='source kswitcher'
alias hyfetch='USER=luna hyfetch'
alias nvtree='tree ~/.config/nvim/'
alias confortavel='cd /mnt/seagate/workspace/coding/projects/bots/confortavel && source /mnt/seagate/workspace/coding/projects/bots/confortavel/env/bin/activate && /mnt/seagate/workspace/coding/projects/bots/confortavel/env/bin/python /mnt/seagate/workspace/coding/projects/bots/confortavel/main.py'
alias recall='bash /mnt/seagate/workspace/coding/projects/scripts/recall-writer/recall-writer.sh'
alias iconsdir='nohup dolphin --new-tab ~/Documentos --new-tab ~/Imagens --new-tab ~/Projetos >/dev/null 2>&1 &'
alias icontabs='nohup dolphin --new-tab /mnt/seagate/unsorted/iconstuff-icon-switcher/substitutes/ --new-tab /home/luan/.local/share/icons/ --new-tab /mnt/seagate/workspace/coding/projects/icons/coral/'
alias icontabs='nohup dolphin --new-tab /mnt/seagate/unsorted/iconstuff-icon-switcher/substitutes/ --new-tab /home/luan/.local/share/icons/ --new-tab /mnt/seagate/workspace/coding/projects/icons/coral/ 2>&1 &'
alias icontabs='dolphin --new-tab /mnt/seagate/unsorted/iconstuff-icon-switcher/substitutes/ --new-tab /home/luan/.local/share/icons/ --new-tab /mnt/seagate/workspace/coding/projects/icons/coral/'
alias worder='cd /mnt/seagate/workspace/coding/projects/scripts/worder && echo python3 main.py'
