alias godot='cd /mnt/seagate/workspace/godot/projects'
alias seagate='cd /mnt/seagate'
alias coding='cd /mnt/seagate/workspace/coding/projects'
alias actvenv='source venv/bin/activate'
alias actenv='source env/bin/activate'
alias nvconf='cd ~/.config/nvim/'
alias kswitcher='source kswitcher'
alias hyfetch='USER=luna hyfetch'
alias nvtree='tree ~/.config/nvim/'
alias confortavel='cd /mnt/seagate/workspace/coding/projects/bots/confortavel && source /mnt/seagate/workspace/coding/projects/bots/confortavel/env/bin/activate && /mnt/seagate/workspace/coding/projects/bots/confortavel/env/bin/python /mnt/seagate/workspace/coding/projects/bots/confortavel/main.py'
