alias seagate='cd /media/luan/seagate'
alias godot='cd /media/luan/seagate/workspace/godot/projects'
alias coding='cd /media/luan/seagate/workspace/coding/projects'
alias actvenv='source venv/bin/activate'
alias actenv='source env/bin/activate'
alias nvtree='tree ~/.config/nvim/'
alias nvconf='cd ~/.config/nvim/'
alias kswitcher='source kswitcher'
alias hyfetch='USER=luna hyfetch'
alias confortavel='cd /media/luan/seagate/workspace/coding/projects/bots/confortavel && source /media/luan/seagate/workspace/coding/projects/bots/confortavel/env/bin/activate && /media/luan/seagate/workspace/coding/projects/bots/confortavel/env/bin/python /media/luan/seagate/workspace/coding/projects/bots/confortavel/main.py'
